tokenizer:
  model_name: google/flan-t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: meteor
  # values:
  #   #- id: rouge_combined
  #   - id: meteor
  #   # - id: rouge
  #   #   args:
  #   #     rouge_type: "rouge1"
  #   # - id: spider
  #   #   args:
  #   #     spice_coeff: 0.0
  #   #     cider_coeff: 1.0
  #   # - id: spider
  #   #   args:
  #   #     spice_coeff: 1.0
  #   #     cider_coeff: 0.0
  #   # # - id: spider
  #   # #   args:
  #   # #     spice_coeff: 0.5
  #   # #     cider_coeff: 0.5


datapool:
  id: real-toxicity-prompts
  args:
    prefix: "complete the sentence: "


env:
  n_envs: 10
  args:
    max_prompt_length: 20
    max_episode_length: 20
    terminate_on_eos: True
    context_start_token: 0
    prompt_truncation_side: "right"


alg:
  id: nlpo
  args:
    n_steps: 128
    batch_size: 4
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 5
    ent_coef: 0.01
  kl_div:
    coeff: 0.01
    target_kl: 1.0
  policy:
    id: maskable_seq2seq_lm_actor_critic_policy
    args:
      model_name: google/flan-t5-base
      apply_model_parallel: True
      prompt_truncation_side: "right"
      mask_type: "learned_top_p"
      top_mask: 0.9
      target_update_iterations: 20
      generation_kwargs:
        do_sample: True
        top_k: 50
        min_length: 5
        max_new_tokens: 20
    
train_evaluation:
  eval_batch_size: 4
  n_iters: 25
  eval_every: 5
  save_every: 20
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
  generation_kwargs:
    num_beams: 5
    min_length: 5
    max_new_tokens: 20

